### ISSUE TITLE
GA が失敗したら貼っていく issue (11/3 17時の確認が失敗した問題)

### ISSUE THREAD

**Issue by tomii9273** [tomii9273/atcoder_after_contest_bot#14]
(日時はすべて日本時間)

### 2023-11-03 17時

https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/6742668645
この1回だけ失敗した。
この前後は正常終了している。

前の失敗 (#12) と同じエラーメッセージ。

```
Traceback (most recent call last):
確認するコンテストと開始時刻の一覧 [('abc326', datetime.datetime(2023, 10, 28, 21, 0)), ('abc325', datetime.datetime(2023, 10, 21, 21, 0))]
abc326 2023-10-28 21:00:00
task_names: ['abc326_a', 'abc326_b', 'abc326_c', 'abc326_d', 'abc326_e', 'abc326_f', 'abc326_g']
abc326_a start
target_id: 47176199
testcases_only_before: set()
testcases_only_after: set()
abc326_b start
target_id: 47176202
testcases_only_before: set()
testcases_only_after: set()
abc326_c start
target_id: 47176208
testcases_only_before: set()
testcases_only_after: set()
abc326_d start
target_id: 47176095
testcases_only_before: set()
testcases_only_after: set()
abc326_e start
target_id: 47175805
testcases_only_before: set()
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 108, in <module>
    check_cases_and_make_tweet()
testcases_only_after: set()
abc326_f start
target_id: 47176079
testcases_only_before: set()
testcases_only_after: set()
abc326_g start
target_id: 47176160
testcases_only_before: set()
testcases_only_after: set()
abc325 2023-10-21 21:00:00
task_names: ['abc325_a', 'abc325_b', 'abc325_c', 'abc325_d', 'abc325_e', 'abc325_f', 'abc325_g']
abc325_a start
target_id: 47176184
testcases_only_before: set()
testcases_only_after: set()
abc325_b start
target_id: 47175751
testcases_only_before: set()
testcases_only_after: set()
abc325_c start
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 51, in check_cases_and_make_tweet
    all_added_cases = get_and_update_added_cases(password)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 175, in get_and_update_added_cases
    testcases_after = get_testcase_names(password, contest_name, task_name, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 104, in get_testcase_names
    .find("table", {"class": "table table-bordered table-striped small th-center"})
     ^^^^
AttributeError: 'NoneType' object has no attribute 'find'
Error: Process completed with exit code 1.
```

**Comment by tomii9273** [comment]
月に1度くらいしか起きないので、早急な対処は必要なさそう。
AtCoder 側の規制であるかもしれない。

古いログは消えてしまうので、エラーが出るたびにこの issue にリンクとログを貼っていく。

12/21 23時 失敗
https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/7289121389
これも規制かも

```
Traceback (most recent call last):
確認するコンテストと開始時刻の一覧 [('agc065', datetime.datetime(2023, 12, 17, 21, 0)), ('abc333', datetime.datetime(2023, 12, 16, 21, 0)), ('abc332', datetime.datetime(2023, 12, 10, 21, 0)), ('arc169', datetime.datetime(2023, 12, 9, 21, 0))]
agc065 2023-12-17 21:00:00
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 108, in <module>
    check_cases_and_make_tweet()
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 51, in check_cases_and_make_tweet
    all_added_cases = get_and_update_added_cases(password)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 175, in get_and_update_added_cases
    testcases_after = get_testcase_names(password, contest_name, task_name, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 126, in get_testcase_names
    testcases = id_to_cases(contest_name, target_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 134, in id_to_cases
    bs = url_to_bs(f"https://atcoder.jp/contests/{contest_name}/submissions/{submission_id}")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 14, in url_to_bs
    with urllib.request.urlopen(url) as res:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/urllib/request.py", line 519, in open
task_names: ['agc065_a', 'agc065_b', 'agc065_c', 'agc065_d', 'agc065_e', 'agc065_f']
agc065_a start
target_id: 48698004
testcases_only_before: set()
testcases_only_after: set()
agc065_b start
target_id: 48697289
testcases_only_before: set()
testcases_only_after: set()
agc065_c start
target_id: 48697732
testcases_only_before: set()
testcases_only_after: set()
agc065_d start
target_id: 48696405
testcases_only_before: set()
testcases_only_after: set()
agc065_e start
target_id: 48657734
testcases_only_before: set()
testcases_only_after: set()
agc065_f start
target_id: 48691138
testcases_only_before: set()
testcases_only_after: set()
abc333 2023-12-16 21:00:00
task_names: ['abc333_a', 'abc333_b', 'abc333_c', 'abc333_d', 'abc333_e', 'abc333_f', 'abc333_g']
abc333_a start
target_id: 48697570
testcases_only_before: set()
testcases_only_after: set()
abc333_b start
target_id: 48697737
testcases_only_before: set()
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/http/client.py", line 1386, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
testcases_only_after: set()
abc333_c start
target_id: 48697971
testcases_only_before: set()
testcases_only_after: set()
abc333_d start
target_id: 48698025
testcases_only_before: set()
testcases_only_after: set()
abc333_e start
target_id: 48698077
testcases_only_before: set()
testcases_only_after: set()
abc333_f start
target_id: 48697776
testcases_only_before: set()
testcases_only_after: set()
abc333_g start
target_id: 48698085
Error: Process completed with exit code 1.
```

**Comment by tomii9273** [comment]
1/6 23時 失敗
https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/7432026065
ABC335 の直後の回

```
Traceback (most recent call last):
確認するコンテストと開始時刻の一覧 [('abc335', datetime.datetime(2024, 1, 6, 21, 0))]
abc335 2024-01-06 21:00:00
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 108, in <module>
task_names: ['abc335_a', 'abc335_b', 'abc335_c', 'abc335_d', 'abc335_e', 'abc335_f', 'abc335_g']
abc335_a start
    check_cases_and_make_tweet()
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 51, in check_cases_and_make_tweet
    all_added_cases = get_and_update_added_cases(password)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 182, in get_and_update_added_cases
    assert testcases_before == set() or testcases_only_before == set()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
target_id: 49059379
target_id: 49124403
testcases_only_before: set()
testcases_only_after: set()
abc335_b start
target_id: 49059407
target_id: 49124395
testcases_only_before: set()
testcases_only_after: set()
abc335_c start
target_id: 49064289
target_id: 49124432
testcases_only_before: set()
testcases_only_after: set()
abc335_d start
target_id: 49065802
target_id: 49124452
testcases_only_before: set()
testcases_only_after: set()
abc335_e start
target_id: 49069090
testcases_only_before: {'test_09.txt', 'sample_01.txt', 'test_57.txt', 'test_89.txt', 'test_69.txt', 'test_35.txt', 'test_56.txt', 'test_10.txt', 'test_22.txt', 'test_48.txt', 'test_52.txt', 'test_51.txt', 'test_86.txt', 'test_20.txt', 'test_81.txt', 'test_55.txt', 'test_83.txt', 'sample_02.txt', 'test_90.txt', 'test_72.txt', 'test_32.txt', 'test_67.txt', 'test_19.txt', 'test_65.txt', 'test_01.txt', 'test_03.txt', 'test_66.txt', 'test_50.txt', 'test_60.txt', 'test_87.txt', 'test_44.txt', 'test_30.txt', 'test_15.txt', 'test_40.txt', 'test_29.txt', 'test_13.txt', 'test_62.txt', 'test_41.txt', 'test_16.txt', 'test_18.txt', 'test_21.txt', 'test_43.txt', 'test_79.txt', 'test_33.txt', 'test_53.txt', 'test_73.txt', 'test_85.txt', 'hand_02.txt', 'test_64.txt', 'test_49.txt', 'test_70.txt', 'test_28.txt', 'test_02.txt', 'hand_01.txt', 'test_58.txt', 'test_42.txt', 'test_84.txt', 'test_06.txt', 'test_37.txt', 'test_80.txt', 'test_63.txt', 'test_07.txt', 'test_26.txt', 'test_14.txt', 'test_68.txt', 'test_17.txt', 'test_59.txt', 'test_39.txt', 'test_08.txt', 'test_71.txt', 'test_11.txt', 'test_34.txt', 'test_77.txt', 'sample_03.txt', 'test_76.txt', 'test_46.txt', 'test_24.txt', 'test_31.txt', 'test_23.txt', 'test_27.txt', 'test_75.txt', 'test_88.txt', 'test_61.txt', 'test_12.txt', 'test_04.txt', 'test_45.txt', 'test_05.txt', 'test_36.txt', 'test_38.txt', 'test_82.txt', 'test_47.txt', 'test_78.txt', 'test_54.txt', 'test_74.txt', 'test_25.txt'}
testcases_only_after: set()
Error: Process completed with exit code 1.
```

**Comment by tomii9273** [comment]
### 2024-07-27 17時

```
Traceback (most recent call last):
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 128, in <module>
確認するコンテストと開始時刻の一覧 [('abc363', datetime.datetime(2024, 7, 20, 21, 0)), ('abc362', datetime.datetime(2024, 7, [13](https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10122038274/job/27993658667#step:5:14), 21, 0))]
abc363 2024-07-20 21:00:00
task_names: ['abc363_a', 'abc363_b', 'abc363_c', 'abc363_d', 'abc363_e', 'abc363_f', 'abc363_g']
abc363_a start
target_id: 55992627
testcases_only_before: set()
testcases_only_after: set()
abc363_b start
    tweets = check_cases_and_make_tweet(*** debug=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 40, in check_cases_and_make_tweet
    all_added_cases = get_and_update_added_cases(*** keep_testcases_txt=debug)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line [17](https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10122038274/job/27993658667#step:5:18)5, in get_and_update_added_cases
    testcases_after = get_testcase_names(password, contest_name, task_name, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 104, in get_testcase_names
    .find("table", {"class": "table table-bordered table-striped small th-center"})
     ^^^^
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by tomii9273** [comment]
### 2024-08-03 17時

https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10226495185

![スクリーンショット 2024-08-06 144720](https://github.com/user-attachments/assets/4ffda3fc-db14-4aff-a45f-493e4bc7abf0)
![スクリーンショット 2024-08-06 144805](https://github.com/user-attachments/assets/7cd1caa5-b1d3-4f45-aaae-5b80c495d404)

```
Traceback (most recent call last):
確認するコンテストと開始時刻の一覧 [('abc364', datetime.datetime(2024, 7, 27, 21, 0)), ('abc363', datetime.datetime(2024, 7, 20, 21, 0))]
abc364 2024-07-27 21:00:00
task_names: ['abc364_a', 'abc364_b', 'abc364_c', 'abc364_d', 'abc364_e', 'abc364_f', 'abc364_g']
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 128, in <module>
    tweets = check_cases_and_make_tweet(*** debug=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 40, in check_cases_and_make_tweet
    all_added_cases = get_and_update_added_cases(*** keep_testcases_txt=debug)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 175, in get_and_update_added_cases
    testcases_after = get_testcase_names(password, contest_name, task_name, None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 104, in get_testcase_names
    .find("table", {"class": "table table-bordered table-striped small th-center"})
abc364_a start
target_id: 56231889
testcases_only_before: set()
testcases_only_after: set()
abc364_b start
target_id: 56231773
testcases_only_before: set()
testcases_only_after: set()
abc364_c start
target_id: 56231994
testcases_only_before: set()
testcases_only_after: set()
abc364_d start
target_id: 56231933
testcases_only_before: set()
testcases_only_after: set()
abc364_e start
target_id: 56231864
testcases_only_before: set()
testcases_only_after: set()
abc364_f start
target_id: 56231969
testcases_only_before: set()
testcases_only_after: set()
abc364_g start
target_id: 56230226
testcases_only_before: set()
testcases_only_after: set()
abc363 2024-07-20 21:00:00
task_names: ['abc363_a', 'abc363_b', 'abc363_c', 'abc363_d', 'abc363_e', 'abc363_f', 'abc363_g']
abc363_a start
target_id: 56232019
testcases_only_before: set()
testcases_only_after: set()
abc363_b start
target_id: 56232062
testcases_only_before: set()
testcases_only_after: set()
abc363_c start
target_id: 56231877
testcases_only_before: set()
testcases_only_after: set()
abc363_d start
     ^^^^
AttributeError: 'NoneType' object has no attribute 'find'
Error: Process completed with exit code 1.
```

headerのものと同じエラー
AtCoder側での規制か
17時の失敗が多いので、この時間は規制がかかりやすいのかも

**Comment by tomii9273** [comment]
### 2024-08-16, 17, 18, 22, 25, 30 いずれも17時

https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10416740587/job/28849573324
https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10430739809/job/28889629404
https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10439000293/job/28907011314
https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10504209943/job/29099165654
https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10545311336/job/29215349001
https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10629108013/job/29465273761

上と同じエラー (`AttributeError: 'NoneType' object has no attribute 'find'`)
今後も頻発するなら、17時の確認は飛ばしてもいいかも

**Comment by tomii9273** [comment]
### 2024-09-09 23時 ～ 09-10 2時

https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10774854399
https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10775924526
https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10776935984
https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10777838371

```
Traceback (most recent call last):
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 128, in <module>
    tweets = check_cases_and_make_tweet(*** debug=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/check_cases_and_make_tweet.py", line 40, in check_cases_and_make_tweet
    all_added_cases = get_and_update_added_cases(*** keep_testcases_txt=debug)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 160, in get_and_update_added_cases
    contest_names_and_times = get_contest_names_and_start_times()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line 43, in get_contest_names_and_start_times
    bs = url_to_bs("https://atcoder.jp/contests/archive")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/atcoder_after_contest_bot/atcoder_after_contest_bot/get_and_update_added_cases.py", line [14](https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10777838371/job/29887840099#step:5:15), in url_to_bs
    with urllib.request.urlopen(url) as res:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/urllib/request.py", line 2[16](https://github.com/tomii9273/atcoder_after_contest_bot/actions/runs/10777838371/job/29887840099#step:5:17), in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable
Error: Process completed with exit code 1.
```

AtCoderメンテナンスのため。
https://x.com/atcoder/status/1833065874267255236

**Comment by tomii9273** [comment]
**今後は特筆すべきエラー以外は、エクセルにまとめたものを貼ることにする。**

### 2024-09-26  ～ 11-11

9/26はGitHub Actionsの障害かも。
その後、いつものAtCoder側の連続アクセス規制によるものと思われるエラーがたまに起きているが、10/26頃からかなりの頻度 (半数以上くらい) で起きるようになったため、以下のPRで対処したところ、それ以来 (11/27現在まで) 起きていない。

- #21

![スクリーンショット 2024-11-27 052343](https://github.com/user-attachments/assets/dc99a292-3337-4529-9ae2-26d7e26a999b)
![スクリーンショット 2024-11-27 052418](https://github.com/user-attachments/assets/966b34cd-0c37-449e-88d6-54c8caa8cf1e)
![スクリーンショット 2024-11-27 052447](https://github.com/user-attachments/assets/f2f99838-5669-446c-8c54-9f8367134022)


### それ以前に起きた、書いていなかったエラー (2024-02-05 ～ 05-25)

![スクリーンショット 2024-11-27 055828](https://github.com/user-attachments/assets/77ec6cb0-75ae-4fe6-9147-72a002f66e8e)
